services:
  app:
    build: .  # Usa el Dockerfile del directorio actual para construir la imagen
    network_mode: "host"
    volumes:
      - ./app:/app    
    environment:
      - AEMET_API_KEY=${AEMET_API_KEY}  # Variable de entorno para la API de AEMET
      - TWITTER_API_KEY=${TWITTER_API_KEY}  # Clave de la API de Twitter
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}  # Secreto de la API de Twitter
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}  # Token de acceso de Twitter
      - TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}  # Secreto del token de acceso
    working_dir: /app  # Directorio de trabajo dentro del contenedor